In [1]:
from __future__ import print_function


In [2]:
import torch

with deep learning framworks we mostly use tensors which are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [3]:
x = torch.empty(5, 3) #making an uninitialized 5X3 matrix 
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [4]:
x = torch.rand(5,3)#a randomly initialized matrix
print(x)

tensor([[0.1455, 0.6945, 0.2747],
        [0.9595, 0.6984, 0.2205],
        [0.5009, 0.7262, 0.8452],
        [0.5101, 0.3282, 0.1689],
        [0.5805, 0.9100, 0.3000]])


In [8]:
x = torch.tensor([5,3]) # tensor using data 

In [9]:
print(x)

tensor([5, 3])


In [12]:
x = x.new_ones(5,3, dtype=torch.double)

In [13]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [14]:
x=torch.rand_like(x,dtype=torch.double)

In [15]:
print(x)

tensor([[0.4263, 0.8347, 0.2205],
        [0.4024, 0.2359, 0.8760],
        [0.9178, 0.8474, 0.9499],
        [0.7106, 0.6495, 0.5087],
        [0.1283, 0.0546, 0.8976]], dtype=torch.float64)


In [16]:
print(x.size())

torch.Size([5, 3])


In [17]:
x.size()

torch.Size([5, 3])

# operations

In [20]:
y = torch.rand(5,3,dtype=torch.double)

In [21]:
print(x + y)

tensor([[0.8929, 1.0774, 0.6829],
        [0.6900, 0.6114, 0.8961],
        [1.2516, 1.1700, 1.6507],
        [1.0418, 1.1971, 0.8761],
        [0.9645, 0.1544, 1.0545]], dtype=torch.float64)


In [22]:
print(torch.add(x,y))

tensor([[0.8929, 1.0774, 0.6829],
        [0.6900, 0.6114, 0.8961],
        [1.2516, 1.1700, 1.6507],
        [1.0418, 1.1971, 0.8761],
        [0.9645, 0.1544, 1.0545]], dtype=torch.float64)


In [24]:
result = torch.empty(5, 3,dtype=torch.double)
torch.add(x, y, out=result)
print(result)

tensor([[0.8929, 1.0774, 0.6829],
        [0.6900, 0.6114, 0.8961],
        [1.2516, 1.1700, 1.6507],
        [1.0418, 1.1971, 0.8761],
        [0.9645, 0.1544, 1.0545]], dtype=torch.float64)


for inplace addition

In [25]:
y.add_(x)

tensor([[0.8929, 1.0774, 0.6829],
        [0.6900, 0.6114, 0.8961],
        [1.2516, 1.1700, 1.6507],
        [1.0418, 1.1971, 0.8761],
        [0.9645, 0.1544, 1.0545]], dtype=torch.float64)

In [27]:
x = torch.rand(4,4)

In [28]:
y = x.view(16)

In [29]:
print(x)

tensor([[0.5160, 0.9457, 0.8154, 0.7306],
        [0.3875, 0.5312, 0.1964, 0.4203],
        [0.2982, 0.7110, 0.4835, 0.2565],
        [0.3633, 0.1019, 0.2744, 0.8395]])


In [30]:
print(y)

tensor([0.5160, 0.9457, 0.8154, 0.7306, 0.3875, 0.5312, 0.1964, 0.4203, 0.2982,
        0.7110, 0.4835, 0.2565, 0.3633, 0.1019, 0.2744, 0.8395])


In [31]:
z = x.view(-1, 8)

In [32]:
print(z)

tensor([[0.5160, 0.9457, 0.8154, 0.7306, 0.3875, 0.5312, 0.1964, 0.4203],
        [0.2982, 0.7110, 0.4835, 0.2565, 0.3633, 0.1019, 0.2744, 0.8395]])


In [33]:
a = torch.ones(5)

In [34]:
b=a.numpy()

In [35]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [36]:
print(b)

[1. 1. 1. 1. 1.]


In [37]:
import numpy as np

In [38]:
a = np.ones(5)
b= torch.from_numpy(a)

In [39]:
print(a)

[1. 1. 1. 1. 1.]


In [40]:
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [41]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1.5160, 1.9457, 1.8154, 1.7306],
        [1.3875, 1.5312, 1.1964, 1.4203],
        [1.2982, 1.7110, 1.4835, 1.2565],
        [1.3633, 1.1019, 1.2744, 1.8395]], device='cuda:0')
tensor([[1.5160, 1.9457, 1.8154, 1.7306],
        [1.3875, 1.5312, 1.1964, 1.4203],
        [1.2982, 1.7110, 1.4835, 1.2565],
        [1.3633, 1.1019, 1.2744, 1.8395]], dtype=torch.float64)
