In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot

In [2]:
data = pd.read_csv("data/data.csv")

In [3]:
data.head()

Country   Age   Salary Purchased
0     Delhi  24.0  72000.0        No
1     mubai  27.0  48000.0       Yes
2  new york  40.0  54000.0        No
3    Madrid  28.0  61000.0        No
4    berlin  40.0      NaN       Yes

In [4]:
x=data.iloc[:,:-1].values
y=data.iloc[:,3].values

In [5]:
x

array([['Delhi', 24.0, 72000.0],
       ['mubai', 27.0, 48000.0],
       ['new york', 40.0, 54000.0],
       ['Madrid', 28.0, 61000.0],
       ['berlin', 40.0, nan],
       ['hong kong', 55.0, 58000.0],
       ['delhi', nan, 52000.0],
       ['new york', 48.0, 79000.0],
       ['mubai', 50.0, 83000.0],
       ['paris', 37.0, 67000.0]], dtype=object)

In [6]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [7]:
from sklearn.preprocessing import Imputer 

In [8]:
imputer = Imputer(missing_values='NaN', strategy ='mean',axis=0)
imputer = imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

In [9]:
x

array([['Delhi', 24.0, 72000.0],
       ['mubai', 27.0, 48000.0],
       ['new york', 40.0, 54000.0],
       ['Madrid', 28.0, 61000.0],
       ['berlin', 40.0, 63777.77777777778],
       ['hong kong', 55.0, 58000.0],
       ['delhi', 38.77777777777778, 52000.0],
       ['new york', 48.0, 79000.0],
       ['mubai', 50.0, 83000.0],
       ['paris', 37.0, 67000.0]], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [11]:
labelencoderX = LabelEncoder()
x[:,0] = labelencoderX.fit_transform(x[:,0])

In [12]:
x

array([[0, 24.0, 72000.0],
       [5, 27.0, 48000.0],
       [6, 40.0, 54000.0],
       [1, 28.0, 61000.0],
       [2, 40.0, 63777.77777777778],
       [4, 55.0, 58000.0],
       [3, 38.77777777777778, 52000.0],
       [6, 48.0, 79000.0],
       [5, 50.0, 83000.0],
       [7, 37.0, 67000.0]], dtype=object)

In [13]:
onehotencoder = OneHotEncoder(categorical_features=[0])
x=onehotencoder.fit_transform(x).toarray()

In [14]:
x

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.40000000e+01, 7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.70000000e+01, 4.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        4.00000000e+01, 5.40000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.80000000e+01, 6.10000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
   

In [15]:
labelencoderY = LabelEncoder()
y = labelencoderY.fit_transform(y)

In [16]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [17]:
from sklearn.cross_validation import train_test_split

D:\anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [18]:
X_train,x_test , Y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
x_test = sc_X.transform(x_test)

In [21]:
X_train 

array([[-0.37796447, -0.37796447,  2.64575131, -0.37796447, -0.37796447,
        -0.37796447, -0.37796447, -0.37796447,  0.27661062,  0.12381479],
       [-0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447,
        -0.37796447, -0.37796447,  2.64575131, -0.02212885,  0.46175632],
       [-0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447,
         2.64575131, -0.37796447, -0.37796447, -1.01792709, -1.53093341],
       [-0.37796447, -0.37796447, -0.37796447,  2.64575131, -0.37796447,
        -0.37796447, -0.37796447, -0.37796447,  0.15490195, -1.11141978],
       [-0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447,
        -0.37796447,  2.64575131, -0.37796447,  1.07324921,  1.7202972 ],
       [-0.37796447,  2.64575131, -0.37796447, -0.37796447, -0.37796447,
        -0.37796447, -0.37796447, -0.37796447, -0.91834726, -0.16751412],
       [ 2.64575131, -0.37796447, -0.37796447, -0.37796447, -0.37796447,
        -0.37796447, -0.37796447, -0.37796447

In [22]:
x_test

array([[-0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447,
        -0.37796447,  2.64575131, -0.37796447,  0.27661062, -0.90166297],
       [-0.37796447, -0.37796447, -0.37796447, -0.37796447, -0.37796447,
         2.64575131, -0.37796447, -0.37796447,  1.27240886,  2.13981082]])