In [1]:
import pandas as pd
import numpy as np

In [4]:
breast = pd.read_csv('data/breast.txt',sep=',',header=0)


In [5]:
breast = breast.replace('?',0)

In [6]:
X_breast = breast.iloc[:,1:10 ].values
y_breast = breast.iloc[:, -1].values

In [7]:
from sklearn.cross_validation import train_test_split

Xb_train, Xb_test, yb_train, yb_test = train_test_split(X_breast, y_breast, test_size = 0.25, random_state = 0)

D:\anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
Xb_train = sc.fit_transform(Xb_train)
Xb_test = sc.transform(Xb_test)

D:\anaconda\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix


In [10]:
breast_classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)
breast_classifier.fit(Xb_train,yb_train)
yb_pred = breast_classifier.predict(Xb_test)
breast_cm = confusion_matrix(yb_test, yb_pred)

In [11]:
breast_cm

array([[102,   6],
       [  6,  61]], dtype=int64)

In [13]:
from sklearn.naive_bayes import GaussianNB
NB_classifier = GaussianNB()
NB_classifier.fit(Xb_train,yb_train)
nb_pred = NB_classifier.predict(Xb_test)
nb_cm = confusion_matrix(yb_test, nb_pred)

In [14]:
nb_cm

array([[102,   6],
       [  2,  65]], dtype=int64)

In [15]:
from sklearn.svm import SVC
svm_classifier = SVC(kernel = 'rbf', random_state = 0)
svm_classifier.fit(Xb_train, yb_train)

# Predicting the Test set results
svm_pred = svm_classifier.predict(Xb_test)

# Making the Confusion Matrix
svm_cm = confusion_matrix(yb_test, svm_pred)

In [16]:
svm_cm

array([[104,   4],
       [  1,  66]], dtype=int64)